### ISSUE TITLE
Error: "panic: empty csv file given"

### ISSUE THREAD

**Issue by 0xdevalias** [anshumanbh/tko-subs#14]
Currently if you run with no parameters you get an ungraceful panic. It would be cool if it defaulted to showing the `-h` output or similar.

```
# ./tko-subs
panic: empty csv file given

goroutine 1 [running]:
main.panicOnError(0x8469c0, 0xc42006ccf0)
	/go/src/github.com/anshumanbh/tko-subs/tko-subs.go:125 +0x4a
main.loadProviders(0x6ffb11, 0x12, 0x0, 0x0, 0x0)
	/go/src/github.com/anshumanbh/tko-subs/tko-subs.go:347 +0x139
main.main()
	/go/src/github.com/anshumanbh/tko-subs/tko-subs.go:74 +0x419
```

**Comment by anshumanbh** [comment]
@0xdevalias Thanks! I will take care of this the next time I push anything to the repo..

**Comment by 0xdevalias** [comment]
Sounds good :) For reference, I seemed to get this because I copied the (statically compiled) binary to a new container, and didn't copy the csv or domains.txt with it.
