### ISSUE TITLE
Panic when start to scan

### ISSUE THREAD

**Issue by butterskinny** [anshumanbh/tko-subs#21]
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x65806c]
> 
> goroutine 9 [running]:
> main.githubCreate(0xc420016800, 0x10, 0xc42004aca0, 0xc42004acb0, 0xc42004acc0, 0xc420016730, 0xc42004acd0, 0xc42004ace0, 0xc42004acf0, 0xc42004ad00, ...)
>         /home/tko-subs/tko-subs.go:167 +0x2fc
> main.takeOverSub(0xc420016800, 0x10, 0xc42001e200, 0x6, 0xc42004aca0, 0xc42004acb0, 0xc42004acc0, 0xc420016730, 0xc42004acd0, 0xc42004ace0, ...)
>         /home/tko-subs/tko-subs.go:138 +0x13e
> main.checkCnameAgainstProviders(0xc420016800, 0x10, 0xc420015260, 0x1a, 0xc420001680, 0x2f, 0x2f, 0xc42004aca0, 0xc42004acb0, 0xc42004acc0, ...)
>         /home/tko-subs/tko-subs.go:293 +0x43e
> main.scanDomain(0xc420016800, 0x10, 0xc420001680, 0x2f, 0x2f, 0xc42004aca0, 0xc42004acb0, 0xc42004acc0, 0xc420016730, 0xc42004acd0, ...)
>         /home/tko-subs/tko-subs.go:249 +0xf2
> main.main.func1(0xc420001680, 0x2f, 0x2f, 0xc42004aca0, 0xc42004acb0, 0xc42004acc0, 0xc420016730, 0xc42004acd0, 0xc42004ace0, 0xc42004acf0, ...)
>         /home/tko-subs/tko-subs.go:101 +0x97
> created by main.main
>         /home/tko-subs/tko-subs.go:100 +0xa9e
>

**Comment by anshumanbh** [comment]
what command did you run?

**Comment by butterskinny** [comment]
I'm tried scan about 500 subdomain 
> tko-subs -domains=subs.txt -data=providers-data.csv -output=output4.csv -takeover -githubtoken=4**

I do not know why, before all was fine.

**Comment by anshumanbh** [comment]
I'd recommend trying without the takeover flag first

**Comment by butterskinny** [comment]
Amazing, it's worked. 
but after 50 subdomain its showing "Domain problem : fork/exec /usr/bin/dig: too many open files"
Am I doing the wrong thing?

**Comment by anshumanbh** [comment]
Umm, try running against a smaller file. Also, check some previous issues here.
