### ISSUE TITLE
Domain problem : dns: failed to unpack truncated message

### ISSUE THREAD

**Issue by chicagohope** [anshumanbh/tko-subs#23]
It's bug?
i'm using ubuntu 16*
can you help me ?

**Comment by chicagohope** [comment]
ok nvm, i change on /etc/resolv.conf with nameserver 8.8.8.8 and error gone.
now i have this one error Domain problem : failed to get authoritative servers; Rcode: 3
no clue. please help.

**Comment by chicagohope** [comment]
also found this one error panic: interface conversion: dns.RR is *dns.DNAME, not *dns.CNAME @anshumanbh

**Comment by anshumanbh** [comment]
Have you tried running the Docker image instead? `docker run -it abhartiya/tools_tkosubs -h`.

Please try that and open this issue again, if you are still seeing this error..
