### ISSUE TITLE
Invalid Memory

### ISSUE THREAD

**Issue by jaikishantulswani** [anshumanbh/tko-subs#26]
Getting this 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x827acf6]

goroutine 2812 [running]:
main.evaluateDomainProvider(0x19ae34d0, 0x10, 0x19916090, 0x28, 0x1965baa0, 0x19704460, 0x1960e6c8, 0x1960e6d0, 0x1960e6d8, 0x1960e6e0, ...)

**Comment by anshumanbh** [comment]
What command did you run?

**Comment by jaikishantulswani** [comment]
Thank you for your reply, I am running this with 
./tko-subs -domains=alldom.txt -data=providers-data.csv -output=possible.csv

**Comment by jaikishantulswani** [comment]
Hello @anshumanbh ,
Any updates !

**Comment by anshumanbh** [comment]
It uses dig so if your workstation doesnt have dig, it wont work. Based on the error above, I can't really tell whats going on here. I recommend using the Docker image. If you still have the same problem with the Docker image, please reopen this issue.

**Comment by jaikishantulswani** [comment]
Dig is already installed by default
