### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by jaikishantulswani** [anshumanbh/tko-subs#27]
Hello @anshumanbh ,
I am including tko-subs into a ruby wrapper but having an issue of using -domains= as filename arg is require # so it failed. Can you please suggest me any workaround.

`system("go run tko-subs/tko-subs.go -domains=  #{filename} -data=providers-data.csv")`

Thank You.

**Comment by anshumanbh** [comment]
I am sorry I can't support wrappers. And, besides I don't know Ruby.
