### ISSUE TITLE
Does tkosubs check for all NS of a particular domain?

### ISSUE THREAD

**Issue by anshumanbh** [anshumanbh/tko-subs#30]
Reference: https://0xpatrik.com/subdomain-takeover-ns/

**Comment by mhmdiaa** [comment]
Yes, it does. We pass each domain to [`authorityReturnRefusedOrServfail()`](https://github.com/anshumanbh/tko-subs/blob/master/tko-subs.go#L357), which iterates over the domain's authoritative nameservers and tries to resolve the domain using them on by one. If at least one of them returns `SERVFAIL`/`REFUSED`, the domain is considered vulnerable.
