### ISSUE TITLE
Provider lists

### ISSUE THREAD

**Issue by kiwiz** [anshumanbh/tko-subs#36]
There's a large number of fingerprints at https://github.com/EdOverflow/can-i-take-over-xyz that would be useful to integrate here.

**Comment by anshumanbh** [comment]
@kiwiz I agree and I do appreciate PRs :)

**Comment by kiwiz** [comment]
Fair enough. Will create a PR with providers I've tested. :]

**Comment by anshumanbh** [comment]
@kiwiz Thanks a lot. Really appreciate it and looking forward to the PR.

**Comment by kiwiz** [comment]
My bad - looking closer at the xyz list, they also include entries that aren't vulnerable. All of the (valid) entries from that list appear to already be supported here.

- Would you be interested in having the non-vulnerable entries added in? IMO it's useful to know about the presence of dangling records, even if not vulnerable.
- It looks like you remove Statuspage.io [here](https://github.com/anshumanbh/tko-subs/commit/25b0c3a498c8d60502837af807a77765e41f580f), though. Was that due to it no longer being vulnerable?
