### ISSUE TITLE
ERROR IN WRITING

### ISSUE THREAD

**Issue by machinexa2** [anshumanbh/tko-subs#38]
---------+
panic: open output.csv: too many open files

goroutine 1 [running]:
main.panicOnError(...)
        /opt/go/src/github.com/anshumanbh/tko-subs/tko-subs.go:125
main.writeResultsToCsv(0xc0040ac000, 0x496, 0x5c7, 0x98cd17, 0xa)
        /opt/go/src/github.com/anshumanbh/tko-subs/tko-subs.go:519 +0x168
main.main()
        /opt/go/src/github.com/anshumanbh/tko-subs/tko-subs.go:117 +0x795

**Comment by machinexa2** [comment]
When it gets a large file as subdomain it gets mad
It scans upto a-d or a-e then it automatically closes without reaching z
It says socket open files or similar

**Comment by riramar** [comment]
https://askubuntu.com/questions/181215/too-many-open-files-how-to-find-the-culprit
