### ISSUE TITLE
github go package not available

### ISSUE THREAD

**Issue by glem0** [anshumanbh/tko-subs#6]
```
glem@ubuntu:~/# go get github.com/anshumanbh/go-github/github
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/anshumanbh/go-github/github: exit status 128
```

The package cannot be accessed by the public.

**Comment by anshumanbh** [comment]
ouch! that hurts...I think I deleted my go-github repo from my github account. can you try go getting the main go-github package and see if that works please?
`go get github.com/google/go-github/`

**Comment by anshumanbh** [comment]
@glen-mac try it now!
